- src/contributing.md
Add basic walkthrough for contributing to the project. #18
> docs: Add contributing workflow walkthrough

- src/CONTRIBUTING.md
> update: CONTRIBUTING.md

- src/CONTRIBUTING.md
> chore: typos, image issues

- src/CONTRIBUTING.md
> chore: image issues

- src/CONTRIBUTING.md
- Fix home directory resolution
- Remove duplicate line
- Add clarification on how to verify success
> fix(docs): Fix the script showing how to configure SSH signing locally

- src/contributing.md
Update the contributing workflow to include a "comment first" section
> Update contributing docs with comment first

- src/u2ws.md
Add unit 2 worksheet with header w/ CSS matching Unit 1.
> Unit 2 worksheet

- src/SUMMARY.md
- src/assets/u1b.md
- src/u2lab.md
> Traffic King commits

- src/u1lab.md
Completed Unit1Lab markdown file.
> Unit1Lab-Completed

- src/u1ws.md
- src/u2ws.md
- src/u3ws.md
✏️  Chore: First pass through to homogenize the formatting and template format of worksheets
❗ Bug fix: Unit 3 embedded YT fix #49
> chore: standardization/cleanup of formatting for worksheets

- src/u1ws.md
- src/u2ws.md
- src/u3ws.md
✅ Patched: Final layout proposal and linting/formatting done for Units 1-3 worksheets #
📃 To Do: Final layout for Labs and Bonus pages
This is the power of linting/formatters 🔥
> chore: final linting/formatting for units 1-3

- src/u5lab.md
> feat: Add unit 5 lab

- src/u5ws.md
Added unit 5 worksheet.
Closes #53
> feat: Add unit 5 worksheet

- src/u7lab.md
u7lab: add content/formatting
Addresses #77
> init: unit 7 lab template

- src/u5ws.md
fix: kolkhis ws5
Addresses #53
> fix: kolkhis needs to learn how to embed :)

- src/assets/deploy/ansible-playbook.yml
- src/development.md
- src/u5ws.md
fix: cargo command req's
fix: video title
chore: clarity and playbook cleanup
chore: clarity
> fix: shebang and cargo requirements

- src/u6intro.md
> Unit 6 init

- src/u5intro.md
> Unit 5 init

- src/u6intro.md
This commit fixes a small writing issue.
> Unit 6 fix

- src/contributing.md
Fixing contributing page youtube video tutorials
> fix: het request

- src/u1intro.md
This commit is fixing writing format
> Unit 1 fix 1.1

- src/u3intro.md
This commit is fixing writing formats
> Unit 3 fix 1.1

- src/u8b.md
Shortened version. Finally closes #88
> feat: Unit 8 bonus

- src/resources.md
- src/u9ws.md
Add unit 9 worksheet.
Closes #86
> feat: Add unit 9 worksheet

- src/intro.md
This commit fixes a typo on intro
> Intro.md fix

- src/resources.md
- src/u7ws.md
- src/u8ws.md
- src/u9ws.md
Add both unit 7 and unit 8 worksheets.
Closes #85 
Closes #84
> feat: Add unit 7 and 8 worksheets

- ref/intro.md
- ref/ulab.md
- ref/uws.md
A little more clear format for the template pages. Hopefully people will also be looking at past work and following suit.
> add: clearer outline and format

- src/u11intro.md
<div class="flex-container">
<p>
<h1>Unit 11: Linux Monitoring</h1>
</p>
</div>
In this unit, we focus on Linux system monitoring, using modern tools like **Grafana, Prometheus, Node Exporter, and Loki**. As Linux administrators, monitoring is essential to ensure system stability, performance, and security across environments.
We will explore how to collect, analyze, and visualize system metrics, and discuss best practices for monitoring and dashboard design that can improve troubleshooting and proactive system management.
Monitoring is a **core responsibility** of Linux system administration, ensuring you know what’s happening under the hood before issues escalate. Modern IT environments rely on monitoring to track system performance, security events, and overall stability — whether in …
> updated u11intro.md

- ref/uws.md
I updated the worksheet style guide to match the changes reflected in previous PRs. Relates to #125  
I added `PLACEHOLDER` with some brief comments on formatting, a few markdown comments, and replaced unit numbers with `N`.
- Removed the `### Introduction` header, intro text moved to the top under the H1. 
- Added formatting instructions for discussion questions and resources.
- Added some instructions to the `Instructions` section.
- I realized we never actually included instructions on what to do with the discussion posts. This PR adds the following to the `Instructions` section (only in the style guide):
```markdown
Fill out this worksheet as you watch the unit video.  
Discussion posts can be completed afterwards, answers to be posted in Discord. 
You must both answer the discussion …
```
> Style guide

- src/contributing.md
- src/development.md
- src/intro.md
- src/resources.md
Lots of miscellaneous changes, transposed resources page to a table
fix: quick link fix
> fix/feat: revamp resources, formatting and clarity

- src/u10ws.md
- src/u1ws.md
- src/u2ws.md
- src/u3ws.md
- src/u4ws.md
- src/u5ws.md
- src/u6ws.md
- src/u7ws.md
- src/u8ws.md
- src/u9ws.md
Modified the instructions sections of current worksheets to include instructions for discussion posts.
> docs: Modify instructions

- src/SUMMARY.md
- src/contributing.md
Porting over some changes from PSC repo and moved contributing links around in summary.md
> fix: summary.md restructure, contributing.md clarity

- src/u3lab.md
- src/u8lab.md
- src/u9lab.md
fix: missing break line, improper header
> refactor: transpose lab 3 verbatim

- src/SUMMARY.md
- src/u7b.md
Added a bonus section for unit 7. Uses tools to check the integrity of packages and files. Closes #87
> feat: Add Unit 7 bonus

- src/u2lab.md
- src/u6lab.md
- src/u9lab.md
Probably prettier thinking its clever
> fix: escaped * characters breaking code block commands

- src/u8intro.md
Took work produced by chigozieum that didn't make it in from the issue and applied it to the file.
Closes #81
> feat: add missing intro page

- src/u1lab.md
Above this change, the file name is fruits.txt (with an s).
> Unit 1 Fix file name in lab

- src/SUMMARY.md
- src/project.md
Added the final project outline. Put it right before unit 1.
Closes #188
> feat: Add final project outline

- src/u12lab.md
This was a long one!
Closes #106
> feat: Add unit 12 lab

- .gitignore
- scripts/generate_resources.sh
Fixes empty list items being added in automatic resource.md generation
> fix: Fix resource generation script

- src/downloads.md
- src/u10lab.md
- src/u10ws.md
- src/u11lab.md
- src/u11ws.md
- src/u12lab.md
- src/u12ws.md
- src/u13lab.md
- src/u13ws.md
- src/u14lab.md
- src/u14ws.md
- src/u15lab.md
- src/u15ws.md
- src/u16lab.md
- src/u9lab.md
- src/u9ws.md
Added download links to the new files added by @cmckee786 to their respective pages and to downloads.md
> feat: Update downloads sections to accomodate new files

- src/u10intro.md
- src/u11intro.md
- src/u4intro.md
- src/u5intro.md
- src/u7lab.md
- src/u7ws.md
- src/u8b.md
- src/u8intro.md
- src/u8lab.md
- src/u8ws.md
- src/u9intro.md
- src/u9lab.md
- src/u9ws.md
> Title changes

- .github/workflows/mdbook.yml
Deleting the cache and changing mdBook version to .45 appeared to fix it on my fork
> test: change mdBook version to 0.4.45

- src/assets/downloads/u1/u1_worksheet.txt
- src/assets/downloads/u15/u15_worksheet.txt
- src/assets/downloads/u2/u2_worksheet.txt
- src/assets/downloads/u3/u3_worksheet.txt
- src/syllabus.md
- src/u10b.md
- src/u10intro.md
- src/u10lab.md
- src/u11lab.md
- src/u12lab.md
- src/u13lab.md
- src/u14b.md
- src/u14lab.md
- src/u15lab.md
- src/u16lab.md
- src/u1lab.md
- src/u2lab.md
- src/u3lab.md
- src/u4lab.md
- src/u5lab.md
- src/u6lab.md
- src/u7lab.md
- src/u8lab.md
- src/u9lab.md
Nuked it with a sed. I considered normalizing line endings with this PR too (they're currently CRLF on most files) but we can do that with a project config.
> chore: Convert the en dash characters to hyphens

- book.toml
- src/u10lab.md
- src/u11lab.md
- src/u12lab.md
- src/u13lab.md
- src/u14lab.md
- src/u15lab.md
- src/u16lab.md
- src/u1lab.md
- src/u2lab.md
- src/u3lab.md
- src/u4lab.md
- src/u5lab.md
- src/u6lab.md
- src/u7lab.md
- src/u8lab.md
- src/u9lab.md
Technically navy is already the default dark theme, thus will be deprecated
fix:reboot lab machine instructions
> fix: default theme

- src/u15ws.md
> added initial worksheet info

- src/u4intro.md
- src/u4lab.md
Fixed up some interesting spacing and double text that was going on with the intro and lab.
> chore: fixup unit 4, removed doubled text

- src/u3intro.md
- src/u3lab.md
- src/u3ws.md
Some code block cleanup and attempt at clarity. Changed title to original from documents provided by Scott
> fix: codeblock clarity, page titles, command prompt clarity

- src/SUMMARY.md
- src/certify.md
Added a page outlining the requirements for earning the certification.
Closes #225
> feat: Add certification info

- src/u10ws.md
- src/u11ws.md
- src/u12ws.md
- src/u13ws.md
- src/u14ws.md
- src/u15ws.md
- src/u5ws.md
- src/u6ws.md
- src/u7ws.md
- src/u8ws.md
- src/u9ws.md
Thanks :argdo and :normal 😄 
closes #246
> fix: migrate u5-16ws.md thread links to forum link

- src/u5ws.md
It was in the original worksheet under `## Lab and Assignment`.  
Also added some minor style adjustments.
> fix: Add network mapping task to digging deeper

- src/assets/downloads/u16/u16_lab.txt
- src/u15lab.md
- src/u16lab.md
> feat: Add unit 16 lab

- src/u10lab.md
- src/u10ws.md
Found this while working through the lab.  Blame it on gipity!
> Removed duplicate Digging deeper/Relection in u10lab

- src/u13b.md
Lot's of oopsies and woopsy daisies
fix: words are hard
fix: words, wordswordswords
> fix(u13-bonus): several clarifications and corrections

- src/u16lab.md
When writing the setup script for the first scenario, I realized that it outlined several things that needed to be true but those things were not *clearly* defined.  
The second scenario had four things that needed to be correct and gave a smaller number than the required criteria.  
I fixed the number and created an ordered list for each item that needs to be completed for the scenario to be completed.
> Clarify u16 lab scenarios

- .gitmodules
Added the git submodule for shared resources. The references to these resources need to be migrated to reference these new locations. See #293
> feat(todo): Add git submodule for shared resources
